[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 3000

[context.production]
  environment = { NODE_VERSION = "18" }