[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**/*"]

[[edge_functions]]
  function = "entry"
  path = "/*"

[dev]
  command = "npm run dev"
  port = 3000

[context.production]
  environment = { NODE_VERSION = "18" }